service: lumen

provider:
    name: aws
    region: us-east-1
    stage: production
    runtime: provided.al2

package:
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/js/**'
        - '!resources/sass/**'
        - '!tests/**'
        - '!database/*.sqlite'

functions:
    web:
        handler: public/index.php
        timeout: 28
        layers:
            - ${bref:layer.php-80-fpm}
        events:
            - httpApi: '*'

plugins:
  - ./vendor/bref/bref
